# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Departamento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='NotaPedidoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='NotaRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nroRemision', models.IntegerField()),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('R', 'Recepcionado')], default='B', max_length=1)),
                ('departamentoDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remision_departamento_destino', to='app.DepartamentoSucursal')),
                ('departamentoOrigen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remision_departamento_origen', to='app.DepartamentoSucursal')),
            ],
        ),
        migrations.CreateModel(
            name='NotaRemisionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo')),
                ('notaRemision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaRemision')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nroRecepcion', models.IntegerField()),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('R', 'Recepcionado')], default='B', max_length=1)),
                ('departamentoDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcion_departamento_destino', to='app.DepartamentoSucursal')),
                ('departamentoOrigen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcion_departamento_origen', to='app.DepartamentoSucursal')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaRemision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recepcion')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='notapedido_detalle',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='notapedido_detalle',
            name='notaPedido',
        ),
        migrations.RemoveField(
            model_name='notapedido',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='notapedido',
            name='origen',
        ),
        migrations.AddField(
            model_name='notapedido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('R', 'Recepcionado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
        migrations.DeleteModel(
            name='NotaPedido_Detalle',
        ),
        migrations.AddField(
            model_name='recepciondetalle',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='notaremisiondetalle',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido'),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notapedidodetalle',
            name='notaPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido'),
        ),
        migrations.AddField(
            model_name='notapedidodetalle',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='notapedido',
            name='departamentoDestino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_departamento_destino', to='app.DepartamentoSucursal'),
        ),
        migrations.AddField(
            model_name='notapedido',
            name='departamentoOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_departamento_origen', to='app.DepartamentoSucursal'),
        ),
    ]
