# Generated by Django 2.0.7 on 2018-08-11 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaarticulo',
            options={'verbose_name_plural': 'Categorias de Artículo'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='departamentosucursal',
            options={'verbose_name_plural': 'Departamentos por Sucursal'},
        ),
        migrations.AlterModelOptions(
            name='notapedido',
            options={'verbose_name_plural': 'Notas de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='notaremision',
            options={'verbose_name_plural': 'Notas de Remisión'},
        ),
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name_plural': 'Recepciones'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'verbose_name_plural': 'Tipos de Artículo'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigoBarras',
            field=models.CharField(max_length=50, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipoArticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TipoArticulo', verbose_name='Tipo de Artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='departamentoDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_departamento_destino', to='app.DepartamentoSucursal', verbose_name='Departamento Destino'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='departamentoOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_departamento_origen', to='app.DepartamentoSucursal', verbose_name='Departamento Origen'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='descripcionUso',
            field=models.CharField(max_length=200, verbose_name='Descripción Uso'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.date(2018, 8, 11), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='nroPedido',
            field=models.IntegerField(verbose_name='Nro Pedido'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='precioAproximado',
            field=models.CharField(max_length=200, verbose_name='Precio Aproximado'),
        ),
        migrations.AlterField(
            model_name='notapedidodetalle',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='notapedidodetalle',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='departamentoDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remision_departamento_destino', to='app.DepartamentoSucursal', verbose_name='Departamento Destino'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='departamentoOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remision_departamento_origen', to='app.DepartamentoSucursal', verbose_name='Departamento Origen'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='nroRemision',
            field=models.IntegerField(verbose_name='Nro Remisión'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido', verbose_name='Nro Pedido'),
        ),
        migrations.AlterField(
            model_name='notaremisiondetalle',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='departamentoDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion_departamento_destino', to='app.DepartamentoSucursal', verbose_name='Departamento Destino'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='departamentoOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion_departamento_origen', to='app.DepartamentoSucursal', verbose_name='Departamento Origen'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='nroRecepcion',
            field=models.IntegerField(verbose_name='Nro Recepción'),
        ),
        migrations.AlterField(
            model_name='recepciondetalle',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
    ]
