# Generated by Django 2.0.7 on 2018-08-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180813_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciondetalle',
            name='cantidadRecivida',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='descripcionUso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Uso'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='precioAproximado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Precio Aproximado'),
        ),
    ]
