# Generated by Django 2.0.7 on 2018-08-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180820_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepciondetalle',
            name='cantidadRecivida',
        ),
    ]
