# Generated by Django 2.0.7 on 2018-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_recepciondetalle_cantidadrecivida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapedido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
    ]
