# Generated by Django 2.0.7 on 2018-08-27 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180825_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
