# Generated by Django 2.0.7 on 2018-08-29 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180827_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 29, 2, 33, 54, 464679, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='nroPedido',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro Pedido'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 29, 2, 33, 54, 465680, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='nroRemision',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro Remisión'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 8, 29, 2, 33, 54, 467687, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='nroRecepcion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro Recepción'),
        ),
    ]
