# Generated by Django 2.0.7 on 2018-09-05 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180903_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 18, 56, 30, 793469, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 18, 56, 30, 795469, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 18, 56, 30, 797469, tzinfo=utc), verbose_name='Fecha'),
        ),
    ]
