# Generated by Django 2.0.7 on 2018-09-05 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20180903_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Plazos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('nombreContacto', models.CharField(max_length=50, verbose_name='Nombre Contacto')),
                ('telefonoContacto', models.CharField(max_length=50, verbose_name='Teléfono Contacto')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 9, 5, 17, 4, 33, 323976, tzinfo=utc), verbose_name='Fecha')),
                ('nroPresupuesto', models.IntegerField(blank=True, null=True, verbose_name='Nro Presupuesto')),
                ('fechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('terminosCondiciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Términos y Condiciones')),
                ('total', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1)),
                ('plazoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PlazoPago', verbose_name='Plazo de Pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proveedor', verbose_name='Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solicitud de Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPresupuestoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo', verbose_name='Artículo')),
                ('solicitudPresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SolicitudPresupuesto')),
                ('unidadMedida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida')),
            ],
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 17, 4, 33, 323976, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 17, 4, 33, 323976, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 17, 4, 33, 323976, tzinfo=utc), verbose_name='Fecha'),
        ),
    ]
