# Generated by Django 2.0.7 on 2018-09-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180905_1304'),
        ('app', '0016_auto_20180905_1500'),
    ]

    operations = [
    ]
