# Generated by Django 2.0.7 on 2018-09-10 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_merge_20180910_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 9, 10, 15, 45, 4, 706772, tzinfo=utc), verbose_name='Fecha')),
                ('nroFacturaCompra', models.IntegerField(blank=True, null=True, verbose_name='Nro Factura Compra')),
                ('total', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Facturas de Compra',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo', verbose_name='Artículo')),
                ('facturaCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FacturaCompra')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 9, 10, 15, 45, 4, 707772, tzinfo=utc), verbose_name='Fecha')),
                ('nroOrdenCompra', models.IntegerField(blank=True, null=True, verbose_name='Nro Orden de Compra')),
                ('fechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('terminosCondiciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Términos y Condiciones')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('total', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo', verbose_name='Artículo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Moneda', verbose_name='Moneda')),
                ('notaCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrdenCompra')),
                ('unidadMedida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida')),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitudpresupuesto',
            options={'verbose_name_plural': 'Solicitudes de Presupuesto'},
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido', verbose_name='Nro Pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 10, 15, 45, 4, 710772, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 10, 15, 45, 4, 712772, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 10, 15, 45, 4, 713772, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 9, 10, 15, 45, 4, 709772, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido', verbose_name='Nro Pedido'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='plazoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PlazoPago', verbose_name='Plazo de Pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturacompradetalle',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='facturacompradetalle',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='ordenCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrdenCompra', verbose_name='Nro Orden Compra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido', verbose_name='Nro Pedido'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='plazoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PlazoPago', verbose_name='Plazo de Pago'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Moneda', verbose_name='Moneda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudpresupuestodetalle',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Moneda', verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
