# Generated by Django 2.0.7 on 2018-10-17 22:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_auto_20180910_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoSucursalAutorizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamentoSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepartamentoSucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autorizadores por Departamento-Sucursal',
            },
        ),
        migrations.CreateModel(
            name='NotaPedidoAutorizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAutorizacion', models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 804238, tzinfo=utc), verbose_name='Fecha')),
                ('gps', models.CharField(blank=True, max_length=50, null=True)),
                ('hashAutorizacion', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='articulo',
            name='codigoActivoFijo',
            field=models.CharField(default=1, max_length=50, verbose_name='Código Activo Fijo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigoBarras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 798223, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 803224, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 805222, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 800223, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 806222, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 22, 59, 23, 801223, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='notapedidoautorizador',
            name='notaPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido'),
        ),
        migrations.AddField(
            model_name='notapedidoautorizador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
