# Generated by Django 2.0.7 on 2018-10-17 23:37

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181017_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPedidoPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FileField(blank=True, null=True, upload_to=app.models.get_file_path_presupuesto)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.AlterModelOptions(
            name='departamentosucursalautorizador',
            options={'verbose_name': 'Autorizador', 'verbose_name_plural': 'Autorizadores por Departamento-Sucursal'},
        ),
        migrations.AlterModelOptions(
            name='notapedidodetalle',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.AddField(
            model_name='notapedidoautorizador',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notapedidoautorizador',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 688226, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 693223, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedidoautorizador',
            name='fechaAutorizacion',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 695222, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 695222, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 689222, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 696232, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 23, 37, 32, 691224, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='notapedidopresupuesto',
            name='notaPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NotaPedido'),
        ),
    ]
