# Generated by Django 2.0.7 on 2018-10-18 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181017_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 122703, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 126701, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedidoautorizador',
            name='fechaAutorizacion',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 128701, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 128701, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 123702, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 130702, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 25, 13, 125701, tzinfo=utc), verbose_name='Fecha'),
        ),
    ]
