# Generated by Django 2.0.7 on 2018-10-18 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181017_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 290933, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 295933, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notapedidoautorizador',
            name='fechaAutorizacion',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 297933, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 297933, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 292933, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 299933, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('PE', 'Borrador'), ('E', 'En Proceso'), ('P', 'Procesado')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 0, 26, 28, 293948, tzinfo=utc), verbose_name='Fecha'),
        ),
    ]
